BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_IDS: [-1]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
SENSORS: [RGB_SENSOR]
VIDEO_OPTION: ["disk"]
VIDEO_DIR: data/videos/cma_da_navigation
TENSORBOARD_DIR: data/tensorboard_dirs/cma_da_intel_video_eval
CHECKPOINT_FOLDER: data/checkpoints/cma_da_intel_train
EVAL_CKPT_PATH_DIR: data/checkpoints/cma_da_intel_train
RESULTS_DIR: data/checkpoints/cma_da_intel_train/video_evals
LOG_FILE: data/logs/cma_da_intel_video_eval.log

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 2
  SAVE_RESULTS: True

MODEL:
  policy_name: CMAPolicy
  ablate_depth: True

  INSTRUCTION_ENCODER:
    bidirectional: True

TASK_CONFIG:
  SIMULATOR:
    HABITAT_SIM_V0:
      GPU_DEVICE_ID: -1
  DATASET:
    SPLIT: val_seen
    DATA_PATH: data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}.json.gz
    SCENES_DIR: data/scene_datasets/
