#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

PYTHON_BIN="${PYTHON_BIN:-python}"

RUN_NAME="${RUN_NAME:-current_cma_rgbd_stop_train500}"
TRAIN_SPLIT="${TRAIN_SPLIT:-train}"
VAL_SPLIT="${VAL_SPLIT:-val_seen}"
MAX_TRAIN_EPISODES="${MAX_TRAIN_EPISODES:-500}"
MAX_VAL_EPISODES="${MAX_VAL_EPISODES:-64}"
MAX_ROLLOUT_EPISODES="${MAX_ROLLOUT_EPISODES:-32}"
MAX_EPOCHS="${MAX_EPOCHS:-20}"
MAX_TRAJECTORY_STEPS="${MAX_TRAJECTORY_STEPS:-160}"
MAX_ROLLOUT_STEPS="${MAX_ROLLOUT_STEPS:-160}"
BATCH_SIZE="${BATCH_SIZE:-4}"
LR="${LR:-5e-5}"
STOP_ACTION_REPEAT="${STOP_ACTION_REPEAT:-4}"
ACTION_LOSS_WEIGHTS="${ACTION_LOSS_WEIGHTS:-1.5,1.0,1.0,1.0}"
USE_DEPTH="${USE_DEPTH:-1}"
SEPARATE_STOP_HEAD="${SEPARATE_STOP_HEAD:-1}"
STOP_THRESHOLD="${STOP_THRESHOLD:-0.55}"
STOP_HEAD_LOSS_WEIGHT="${STOP_HEAD_LOSS_WEIGHT:-1.0}"

export RUN_NAME
export TRAIN_SPLIT
export VAL_SPLIT
export MAX_TRAIN_EPISODES
export MAX_VAL_EPISODES
export MAX_ROLLOUT_EPISODES
export MAX_EPOCHS
export MAX_TRAJECTORY_STEPS
export MAX_ROLLOUT_STEPS
export BATCH_SIZE
export LR
export STOP_ACTION_REPEAT
export ACTION_LOSS_WEIGHTS
export USE_DEPTH
export SEPARATE_STOP_HEAD
export STOP_THRESHOLD
export STOP_HEAD_LOSS_WEIGHT

CUDA_VISIBLE_DEVICES= \
PYTHONPATH="../habitat-baselines:../habitat-lab:." \
"${PYTHON_BIN}" \
  scripts/current_habitat_cma_da_train.py
